name: gplw-rc
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scipy
  - openpyxl
  - xarray
  - netcdf4
  - tqdm
  - numba
  - geopandas
  - cartopy
  - pip
